name: promad_sora
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intro_slider: ^4.2.1
  flutter_screenutil: ^5.9.0
  material_design_icons_flutter: ^7.0.7296
  stylish_bottom_bar: ^1.0.3
  simple_gradient_text: ^1.3.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/cat1.jpeg
    - assets/img/cat2.jpeg
    - assets/img/cat3.jpeg
    - assets/img/cat4.jpeg
    - assets/img/cat5.jpeg
    - assets/img/cat6.jpeg
    - assets/img/cat7.jpeg
    - assets/img/cat8.jpeg

  fonts:
    - family: Nexa_Regular
      fonts:
        - asset: assets/font/Nexa-Trial-Regular.otf
    - family: Nexa_Heavy
      fonts:
        - asset: assets/font/Nexa-Trial-Heavy.otf
    - family: Nexa_Bold
      fonts:
        - asset: assets/font/Nexa-Trial-Bold.otf
    - family: Nexa_Light
      fonts:
        - asset: assets/font/Nexa-Trial-Light.otf